# .github/workflows/run-tests.yml

# A name for this workflow, which will be shown on GitHub
name: Run Python Unit Tests

# 1. Trigger Configuration
# This section defines when the workflow will run.
# It's set to run on every push to the 'main' branch,
# and also on any pull request that targets the 'main' branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. Jobs Configuration
# A workflow is made up of one or more jobs that can run in parallel or sequentially.
jobs:
  # The 'build' job is the only job in this workflow.
  build:
    # Specifies the type of machine to run the job on.
    # 'ubuntu-latest' is a standard, reliable choice for most projects.
    runs-on: ubuntu-latest

    # 3. Steps Configuration
    # A job contains a sequence of tasks called steps.
    steps:
      # Step 1: Check out the repository code
      # This action checks out your repository onto the runner,
      # allowing the workflow to access your code and test files.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      # This action installs a specific version of Python on the runner.
      # It's good practice to specify the version you develop with.
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      # This step runs shell commands to install any libraries your project needs.
      # Here, we are installing 'pytest', a popular testing framework.
      # If you had a requirements.txt file, you would install it here:
      # pip install -r requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Step 4: Run the tests
      # This is the final step where the tests are actually executed.
      # The 'pytest' command will automatically discover and run the tests
      # in your repository (files named test_*.py or *_test.py).
      - name: Run tests with pytest
        run: |
          pytest

